
hull:
  config:
    general:
      fullnameOverride: zero-bin
    specific:
      version: develop
  objects:
    deployment:
      leader:
        replicas: 1
        pod:
          containers:
            leader:
              image:
                repository: us.gcr.io/immutable-418115/zero-bin-leader
                tag: _HT*hull.config.specific.version
              env:
                AMQP_URI:
                  valueFrom: 
                    secretKeyRef:
                      staticName: true
                      name: rmq-credentials
                      key: amqp_uri
                PALADIN_AMQP_URI:
                  valueFrom: 
                    secretKeyRef:
                      staticName: true
                      name: rmq-credentials
                      key: amqp_uri
                PALADIN_RUNTIME:
                  value: AMQP
                SERVER_ADDR:
                  value: 0.0.0.0:8080
                ARITHMETIC_CIRCUIT_SIZE:
                  value: 16..23
                BYTE_PACKING_CIRCUIT_SIZE:
                  value: 9..21
                CPU_CIRCUIT_SIZE:
                  value: 12..25
                KECCAK_CIRCUIT_SIZE:
                  value: 14..20
                KECCAK_SPONGE_CIRCUIT_SIZE:
                  value: 9..15
                LOGIC_CIRCUIT_SIZE:
                  value: 12..18
                MEMORY_CIRCUIT_SIZE:
                  value: 17..28
                RUST_LOG:
                  value: info
              ports:
                http:
                  containerPort: 8080
              resources:
                limits:
                  cpu: 2
                  memory: 6Gi
                requests:
                  cpu: 1
                  memory: 2Gi
              command:
                - coordinator
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 60
                periodSeconds: 5
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 10
                periodSeconds: 5
      worker:
        replicas: 1 # CHANGEME
        pod:
          containers:
            worker:
              image:
                repository: us.gcr.io/immutable-418115/zero-bin-worker
                tag: _HT*hull.config.specific.version
              env:
                AMQP_URI:
                  valueFrom: 
                    secretKeyRef:
                      staticName: true
                      name: rmq-credentials
                      key: amqp_uri
              resources:
                limits:
                  cpu: 2
                  memory: 6Gi
                requests:
                  cpu: 1
                  memory: 2Gi
    service:
      leader:
        type: ClusterIP # Can change to LoadBalancer
        ports:
          http:
            port: 8080
            targetPort: 8080